### ISSUE TITLE
Design a logo

### ISSUE THREAD

**Issue by raynescc** [raynescc/project-n#1]
Design a logo for a non-profit organisation that gives 'Irish Dancing' lessons. The logo will be used on Facebook, Twitter and the website. Please provide a logo with no white background :)

The best logo will be used, but we welcome anyone to submit one. Put the logo in the /logos folder.

**Comment by redoverture** [comment]
@raynescc What is the organization's name?

**Comment by raynescc** [comment]
Hey @redoverture apologies for the slow reply. The organisation is called: CAID Clerk
